[package]
name = "elysium"
version = "0.1.0"
authors = [ "bepzi <bepzi@bepzi.com>" ]
edition = "2018"
license = "GPL-3.0-or-later"
publish = false

[lib]
crate_type = [ "staticlib" ]

[dependencies]
cxx = "1"
rand = "0.8"

[build-dependencies]
cxx-build = "1"
